USE [master]
GO

/****** Object:  Database [Загадка]    Script Date: 12.02.2022 18:12:35 ******/
CREATE DATABASE [Загадка]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Загадка', FILENAME = N'C:\Users\asya1\Desktop\MSSQL15.SQLEXPRESS\MSSQL\DATA\Загадка.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Загадка_log', FILENAME = N'C:\Users\asya1\Desktop\MSSQL15.SQLEXPRESS\MSSQL\DATA\Загадка_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Загадка].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Загадка] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Загадка] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Загадка] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Загадка] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Загадка] SET ARITHABORT OFF 
GO

ALTER DATABASE [Загадка] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Загадка] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Загадка] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Загадка] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Загадка] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Загадка] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Загадка] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Загадка] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Загадка] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Загадка] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Загадка] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Загадка] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Загадка] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Загадка] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Загадка] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Загадка] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Загадка] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Загадка] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Загадка] SET  MULTI_USER 
GO

ALTER DATABASE [Загадка] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Загадка] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Загадка] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Загадка] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Загадка] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Загадка] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Загадка] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Загадка] SET  READ_WRITE 
GO

